sudo: true
language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "pip install codecov"
  - "pip install psycopg2"

services:
  - postgres
  
before_script:
  - psql -c "CREATE DATABASE test_libapp;" -U postgres
  
script:
- nosetests  --with-coverage 
after_success:
- coveralls